### ISSUE TITLE
Have an docker environment to run the website locally

### ISSUE THREAD

**Issue by knmcguire** [ROS-Aerial/aerial_robotic_landscape#36]
For [my personal website ](https://github.com/knmcguire/knmcguire.github.io) based on github pages I used to have a really handy docker-compose.yml (with `docker-compose up`) that I wanted to use for our github pages here too.

The content is:
```
version: '2.2'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll

```
But this no longer works, which is due to the issue mentioned by github itself: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll#building-your-site-locally

> Note: If you've installed Ruby 3.0 or later (which you may have if you installed the default version via Homebrew), you might get an error at this step. That's because these versions of Ruby no longer come with webrick installed.
> 
> To fix the error, try running bundle add webrick, then re-running bundle exec jekyll serve.

I'm still figuring out how to add this to the docker-compose.yml since just adding it to the command doesn't work.
